/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azmi
 */
public class PencatatanHarianGUI extends javax.swing.JFrame {

    /**
     * Creates new form PencatatanHarianGUI
     */
    public PencatatanHarianGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTugas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taTugas = new javax.swing.JTextArea();
        tfNama = new javax.swing.JTextField();
        tfTanggal = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapustbl = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 47, 68));

        jLabel1.setText("Pencatatan Harian ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setText("Nama:");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Yang Ingin Dilakukan");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah di kerjakan ", "Belum di Kerjakan " }));

        jLabel5.setText("Status");

        tbTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Tanggal", "Tugas", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbTugas);

        taTugas.setColumns(20);
        taTugas.setRows(5);
        jScrollPane2.setViewportView(taTugas);

        tfTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTanggalActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(51, 102, 255));
        btnSimpan.setText("Simpan Perubahan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(102, 255, 102));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(153, 153, 153));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(153, 255, 51));
        btnTambah.setText("Tambah Tabel");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapustbl.setBackground(new java.awt.Color(255, 51, 51));
        btnHapustbl.setText("Hapus Tabel");
        btnHapustbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapustblActionPerformed(evt);
            }
        });

        btnExport.setBackground(new java.awt.Color(102, 102, 255));
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKeluar)))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnHapustbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnExport))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                .addComponent(tfNama))
                                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 268, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapustbl)
                    .addComponent(btnExport))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // Mengambil model dari tabel (DefaultTableModel) yang ada di objek tbTugas
        DefaultTableModel model = (DefaultTableModel) tbTugas.getModel();
        
        // Memeriksa apakah tidak ada baris yang dipilih di tabel
        if (tbTugas.getSelectedRow() == 1) {
            // Memeriksa apakah tabel tidak memiliki baris
            if (tbTugas.getRowCount() == 0) {
                // Menampilkan pesan jika tidak ada baris untuk dipilih
                JOptionPane.showMessageDialog(null, "Pilih tugas yang mau pertama");
            } else {
                // Menampilkan pesan jika tidak ada baris yang dipilih
                JOptionPane.showMessageDialog(null, "pilih tugas yang mau di hapus");
            }
        } else {
            // Jika ada baris yang dipilih, mengubah nilai pada model tabel dengan nilai dari input
            model.setValueAt(tfNama.getText(), tbTugas.getSelectedRow(), 0);
            model.setValueAt(tfTanggal.getText(), tbTugas.getSelectedRow(), 1);
            model.setValueAt(cbStatus.getSelectedItem(), tbTugas.getSelectedRow(), 3);
            model.setValueAt(taTugas.getText(), tbTugas.getSelectedRow(), 2);
            
            
            // Mengaktifkan tombol tambah (btnTambah)
            btnTambah.setEnabled(true);
            
            // Menampilkan pesan sukses bahwa tugas sudah diubah
            JOptionPane.showMessageDialog(null, "tugas sudah di ubah");
            
            // Mengosongkan nilai pada input setelah tugas diubah
            tfNama.setText("");
            tfTanggal.setText("");
            cbStatus.setSelectedItem("Sudah di Kerjakan ");
            taTugas.setText("");

        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // Menampilkan dialog konfirmasi dengan opsi Yes/No dan menyimpan hasilnya dalam variabel 'a'
        int a = JOptionPane.showConfirmDialog(null, "apakah anda ingin keluar", "select", JOptionPane.YES_NO_OPTION);
        // Blok kode di bawah akan dieksekusi jika pengguna memilih opsi 'Yes' (JOptionPane.YES_OPTION)
        {
            // Keluar dari program dengan menghentikan eksekusi (System.exit(0))    
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // Mengambil model dari tabel (DefaultTableModel) yang ada di objek tbTugas
        DefaultTableModel model = (DefaultTableModel) tbTugas.getModel();
        
        // Memeriksa apakah input nama, tanggal, atau tugas kosong
        if (tfNama.getText().trim().equals("") || tfTanggal.getText().trim().equals("") || taTugas.getText().trim().equals("")) {
            // Menampilkan pesan kesalahan jika ada input yang kurang lengkap
            JOptionPane.showMessageDialog(null, "Tugas yang anda isi kurang lengkap \n silahkan isi dengan lengkap");
        } else {
            // Jika input lengkap, menambahkan baris baru ke model tabel dengan data dari input
            model.addRow(new Object[]{tfNama.getText(), tfTanggal.getText(), taTugas.getText(), cbStatus.getSelectedItem()});
            // Menampilkan pesan sukses jika tugas berhasil diinput
            JOptionPane.showMessageDialog(null, "tugas anda berhasil di input");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // Mengosongkan isi teks pada JTextField dengan variabel tfNama
        tfNama.setText("");
        // Mengosongkan isi teks pada JTextField dengan variabel tfTanggal
        tfTanggal.setText("");
        // Mengatur pilihan default pada JComboBox dengan variabel cbStatus ke "Sudah di kerjakan"
        cbStatus.setSelectedItem("Sudah di kerjakan");
        // Mengosongkan isi teks pada JTextArea dengan variabel taTugas
        taTugas.setText("");
        // Memfokuskan kursor ke JTextField dengan variabel tfNama
        tfNama.requestFocus();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // Mengambil model dari tabel (DefaultTableModel) yang ada di objek tbTugas
        DefaultTableModel model = (DefaultTableModel) tbTugas.getModel();
        
        // Memeriksa apakah tidak ada baris yang dipilih di tabel
        if (tbTugas.getSelectedRow() == -1) {
            // Memeriksa apakah baris pertama dipilih (0)
            if (tbTugas.getSelectedRow() == 0) {
                // Menampilkan pesan kesalahan jika baris pertama yang dipilih
                JOptionPane.showMessageDialog(null, "anda belum memilih tugas ");
            } else {
                // Menampilkan pesan kesalahan jika tidak ada baris yang dipilih
                JOptionPane.showMessageDialog(null, "Silahkan Pilih Tugas");
            }
        } else {
            // Jika ada baris yang dipilih, mengisi nilai input dengan nilai dari baris yang dipilih
            tfNama.setText(model.getValueAt(tbTugas.getSelectedRow(), 0).toString());
            tfTanggal.setText(model.getValueAt(tbTugas.getSelectedRow(), 1).toString());
            cbStatus.setSelectedItem(model.getValueAt(tbTugas.getSelectedRow(), 3).toString());
            taTugas.setText(model.getValueAt(tbTugas.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapustblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapustblActionPerformed
        // Mengambil model dari tabel (DefaultTableModel) yang ada di objek tbTugas
        DefaultTableModel model = (DefaultTableModel) tbTugas.getModel();
        
        // Memeriksa apakah tidak ada baris yang dipilih di tabel
        if (tbTugas.getSelectedRow() == -1) {
            // Memeriksa apakah baris pertama (indeks 0) yang dipilih
            if (tbTugas.getSelectedRow() == 0) {
                // Menampilkan pesan kesalahan jika baris pertama yang dipilih
                JOptionPane.showMessageDialog(null, "Pilih tugas yang ingin di hapus");
            } else {
                // Menampilkan pesan kesalahan jika tidak ada baris yang dipilih
                JOptionPane.showMessageDialog(null, "Pilih tugas yang di hapus");
            }
        } else {
            // Menghapus baris yang dipilih dari model tabel
            model.removeRow(tbTugas.getSelectedRow());
            
            // Menampilkan pesan sukses bahwa data tugas berhasil dihapus
            JOptionPane.showMessageDialog(null, "Data tugas Berhasil di hapus");
        }
        // Mengosongkan nilai pada input setelah tugas dihapus
        tfNama.setText("");
        tfTanggal.setText("");
        cbStatus.setSelectedItem("sudah di kerjakan");
        taTugas.setText("");
        
        // Memfokuskan kursor ke JTextField dengan variabel tfNama
        tfNama.requestFocus();
    }//GEN-LAST:event_btnHapustblActionPerformed

    private void tfTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        try {
             // Membuka file "ExportData.txt" untuk ditulis menggunakan BufferedWriter
            BufferedWriter bw = new BufferedWriter(new FileWriter("ExportData.txt"));
            
            // Iterasi melalui setiap baris (rows) pada tabel (tbTugas)
            for (int i = 0; i < tbTugas.getRowCount(); i++) { //membaca rows table
                for (int j = 0; j < tbTugas.getColumnCount(); j++) { //membaca column table
                    bw.write(tbTugas.getValueAt(i, j).toString() + " ");
                }
                // Menambahkan baris baru setelah semua kolom pada baris tertentu telah ditulis
                bw.newLine();
            }
            
            // Menampilkan pesan sukses bahwa data berhasil diexport
            JOptionPane.showMessageDialog(null, "Data Berhasil Export");
            
            // Menutup BufferedWriter setelah selesai menulis
            bw.close();
        } catch (Exception e) {
            // Menangani exception jika terjadi kesalahan
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PencatatanHarianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PencatatanHarianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PencatatanHarianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PencatatanHarianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PencatatanHarianGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapustbl;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taTugas;
    private javax.swing.JTable tbTugas;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTanggal;
    // End of variables declaration//GEN-END:variables
}
